### ISSUE TITLE
No permission?

### ISSUE THREAD

**Issue by Amantis1** [StarGazer1258/BeatDrop#105]
![helpo](https://user-images.githubusercontent.com/58264568/69735476-bd300580-10fe-11ea-9f6b-1f67c744287c.png)
![help2](https://user-images.githubusercontent.com/58264568/69735477-bd300580-10fe-11ea-856f-a813706f993b.png)
![help3](https://user-images.githubusercontent.com/58264568/69735478-bd300580-10fe-11ea-8cdf-57306d778411.png)

**Environment:**
Device - Device Manufacturer, Model Number, and Revision
OS - Operating System Type, Version, and Build Number
BeatDrop Version - BeatDrop Version including build tags

**Description of bug:**

**Steps to reproduce:**

**Expected behavior:**

**Actual Behavior**
A clear and concise description of what actually happened.

**Screenshots:**

**Comment by StarGazer1258** [comment]
Further information is required. Please fill out all sections of the bug report template and this issue will be reopened.
