### ISSUE TITLE
Can't put the song in the playlist

### ISSUE THREAD

**Issue by lolozin111** [StarGazer1258/BeatDrop#113]
**Environment:**
Device - Device Manufacturer, Model Number, and Revision
OS - Operating System Type, Version, and Build Number
BeatDrop Version - BeatDrop Version including build tags

**Description of bug:**

**Steps to reproduce:**

**Expected behavior:**

**Actual Behavior**
A clear and concise description of what actually happened.

**Screenshots:**
![image](https://user-images.githubusercontent.com/59100795/71293675-285aa980-2344-11ea-99b1-1a917c5540ad.png)

**Comment by StarGazer1258** [comment]
Further information is required. Please fill out all sections of the bug report template and this issue will be reopened.
