### ISSUE TITLE
Beatdrop 2.5.9 connection error

### ISSUE THREAD

**Issue by Hellzbellz123** [StarGazer1258/BeatDrop#117]
**Environment:**
Device - Oculus?, Rift S
OS - Windows, 10, and 1909(OS Build 18363.535)
BeatDrop Version - 2.5.9

**Description of bug:**
Clicking any of the Beatsaver/mod lookup doesnt work properly

**Steps to reproduce:**
1. Go to beatsaver tab
2. Click on new songs/top finished/top downloaded
3. nothing loads

beatmods recommended section does the same thing while the all tab works as intended

**Expected behavior:**
songs/mods to load
**Actual Behavior**
little loading icon goes forever. after a bit it says something about the connection but i still have internet.

**extra info**
running as admin didnt fix anything or break anything

**Comment by 1DontEx1st** [comment]
Same with Steam install on Windows v1903 (build 18362.535)

**Comment by helix7089** [comment]
Same issue

**Comment by CCTrollz** [comment]
Same details and issue

**Comment by Slluxx** [comment]
same

**Comment by CharlotteDunois** [comment]
Same, also tested with 2.6.0-beta and 2.6.1-beta.

**Comment by Alvacia** [comment]
Same since yesterday (Steam and Windows 18362.535)

**Comment by AverytheFurry** [comment]
same

**Comment by dsrdakota** [comment]
It seams like a server is down, as stable and beta version both produce the same problem.

**Comment by fallyoverguy** [comment]
I am having the same problem.

**Comment by CharlotteDunois** [comment]
Note: It seems to work now.

**Comment by craig395** [comment]
> Note: It seems to work now.

Was not working for me yesterday and is now working. Must have been some service issue.

**Comment by StarGazer1258** [comment]
The issue was caused by a rapid surge of traffic generated by BeatDrop users over the holidays. This prompted beatsaver administrators to block BeatDrop from the service. BeatDrop has been unblocked and service should be available as usual. Please be courteous with your use of DeatDrop (do not spam requests) while we investigate what may have caused this surge. Thanks!

**Comment by 1DontEx1st** [comment]
My guess - new VR-owners finding this awesome tool :)
