### ISSUE TITLE
trying to display my 3k song library, beatdrop hangs at a blank white window

### ISSUE THREAD

**Issue by telos00** [StarGazer1258/BeatDrop#12]
**Environment:**
Device - Alienware 17R4, i7-7820HK, GTX 1080, 32 GB RAM
OS - Windows 10, 1903 Insider, and 18362.53
BeatDrop Version - 2.1.8

**Description of bug:**
If I try to go to Library->Songs, BeatDrop sits there with the bouncing balls for a while, then hangs with a blank white window. 

**Steps to reproduce:**
1. Start BeatDrop
2. Click on Library -> Songs
3. Wait a few seconds.
4. I see a flash of what looks like the song list for a short instant.
5. App hangs with a blank white window.

**Expected behavior:**
My list of songs should be displayed.

**Actual Behavior**
I see a short flash of what looks like a list of songs, then the app hangs with a blank white window.

**Screenshots:**
First I see this:
![image](https://user-images.githubusercontent.com/49680782/56206200-a968e080-6000-11e9-8c51-d5a9c593e1d5.png)
Then I see this for a fraction of a second:
![image](https://user-images.githubusercontent.com/49680782/56206311-ecc34f00-6000-11e9-9e08-4c7b91c90527.png)

And then the app hangs with a blank white window:
![image](https://user-images.githubusercontent.com/49680782/56206345-fe0c5b80-6000-11e9-9319-4d1e864f93a0.png)

Some other maybe useful information:
- I have nearly 3k songs.
- Beat Saber is installed to D:\Games\Steam\steamapps\common\Beat Saber
- all drives are fast SSDs.
- Beat Drop 1 had no problems
- my songs folder has a mix of subfolders in the 0000-0000 number format and some with the name of the song

**Comment by StarGazer1258** [comment]
Can you go to settings and click on the “Scan for Songs” button, then try again?

**Comment by telos00** [comment]
> Can you go to settings and click on the “Scan for Songs” button, then try again?

I'll try that tonight when I get the chance. Are there any traces or logs you want me to collect?

**Comment by telos00** [comment]
Clicking "Scan for Songs" gives me a progress bar for a few seconds, that's it. After the progress bar closes, if I click Library->Songs, it shows a song list for a short time, but the app almost immediately hangs again with a blank white window.

**Comment by Thelete** [comment]
I get the same blank screen just starting the program
