### ISSUE TITLE
Not Able to Download Anything - Hash Error

### ISSUE THREAD

**Issue by icanhearyousmile** [StarGazer1258/BeatDrop#121]
Getting Hash download errors for all the songs I've tried so far. Have tried 
- Party like its 1923
- Red Velvet - Red Flavor
- Red Velvet - Sassy Me

![image](https://user-images.githubusercontent.com/35151483/71636446-37701000-2bfe-11ea-8071-bb6da72f7ebf.png)

Playing on Valve Index on Win10 machine, uninstalled and reinstalled mods today after search wasn't working; Got the search to work but unable to download anything. Fiber internet connection, computer connected directly to LAN.

**Comment by Eveleyy** [comment]
Same issue. Got BeatDrop working the first time I installed it. Every song I try to download now have this error message.

I tried to fully reset the software, uninstall and reinstall it. Same issue.

Playing with a Rift S, Win10. Fiber connection, computer connected directly to LAN aswell.

![image](https://user-images.githubusercontent.com/14355586/71856486-6990de80-30e4-11ea-9bff-da4245bd5970.png)

**Comment by StarGazer1258** [comment]
# For future discussion
Please refrain from commenting "Same here" or the like. It adds very little to the conversation and just clutters the timeline. If you are experiencing  the same issue, please use the "thumbs up" button on the original post instead.  
  
Thank you!

**Comment by M0NsTeRRR** [comment]
Fix suggest #144

**Comment by Guenevierre** [comment]
I have been having this same issue for about a month. I have uninstalled Beat Drop, deleted all the folders to clear cache and reinstalled the program, and I continue to get the same Hash error.

Song 32e
![BeatDropError](https://user-images.githubusercontent.com/64238356/80168183-33eb0500-85b0-11ea-905f-eff1053c218e.png)

Ava Max - Salt
![BeatDropError2](https://user-images.githubusercontent.com/64238356/80168130-187ffa00-85b0-11ea-994c-28f9fc590bdc.png)

**Comment by TakuyaTomioka** [comment]
Same here ...

**Comment by MaverickMartyn** [comment]
> Same here ...

I'm sorry, but did you not read the massive notice in the second post here?
Use the thumbs up button on the original post instead, please.

**Comment by mindyh** [comment]
Just installed 2.6.2 and running into this same issue. Did a little snooping on fix #144 that shipped with this version, looks like the first linked URL is still breaking - http://www.beatsaver.com/api/download/key/7d51   gives Error 525 SSL Handshake failed now instead of 404.
