### ISSUE TITLE
beatdrop keeps crashing

### ISSUE THREAD

**Issue by Shepard87** [StarGazer1258/BeatDrop#128]
i have beat saber for oculus and im trying to load up beat drop and im not sure where its supposed to be installed
**Environment:**
Device - Device Manufacturer, Model Number, and Revision
OS - Operating System Type, Version, and Build Number
BeatDrop Version - BeatDrop Version including build tags

**Description of bug:**

**Steps to reproduce:**

**Expected behavior:**

**Actual Behavior**
A clear and concise description of what actually happened.

**Screenshots:**

**Comment by StarGazer1258** [comment]
Further information is required. Please fill out all sections of the bug report template and this issue will be reopened.
