### ISSUE TITLE
when looking at the list of new songs on beatsaver.com please display the upload time

### ISSUE THREAD

**Issue by telos00** [StarGazer1258/BeatDrop#13]
**Environment:**
Device - Alienware 17R4
OS - Windows 10, Insider 1903, 18362.53
BeatDrop Version - BeatDrop Version 2.1.8

**Description of bug:**
When scrolling through the list of new songs on Beat Saver, please include the upload time as part of the metadata displayed. I use this to track where to start looking for new songs, and it's inconvenient it's not displayed. 
Also it would be cool if you could jump to a certain upload time.

**Steps to reproduce:**
1. Go to BeatSaver.
2. Click on 'new songs'
3. Look at the songs displayed.
4. Notice the upload time is not displayed.

**Expected behavior:**
the upload time should be displayed as part of the song's metadata.

**Actual Behavior**
other stuff is displayed but the upload time is missing.

**Screenshots:**
![image](https://user-images.githubusercontent.com/49680782/56206893-4415ef00-6002-11e9-89b8-c7c1212c1935.png)

**Comment by brandonhenry** [comment]
Added
