### ISSUE TITLE
Beatdrop crash

### ISSUE THREAD

**Issue by BlubberyChenG** [StarGazer1258/BeatDrop#130]
**Environment:**
Device - Device Manufacturer, Model Number, and Revision
OS - Operating System Type, Version, and Build Number
BeatDrop Version - BeatDrop Version including build tags

**Description of bug:**

**Steps to reproduce:**

**Expected behavior:**

**Actual Behavior**
A clear and concise description of what actually happened.

**Screenshots:**

![Beatdrop](https://user-images.githubusercontent.com/59504847/71765465-5ff55400-2ef5-11ea-91b0-db7fb34f5342.PNG)

**Comment by stardust1330** [comment]
i just reinstalled the latest version and made sure to delete appdata for beatdrop. It fixed it for me.

**Comment by lmichaela94** [comment]
TypeError
    in t
    in Connect(t)
    in Ga
    in div
    in div
    in t
    in Connect(t)
    in div
    in t
    in Connect(t)
    in t
    in t
    in t

had the same issue but this was the full text of the crash text

**Comment by StarGazer1258** [comment]
Further information is required. Please fill out all sections of the bug report template and this issue will be reopened.
