### ISSUE TITLE
Whenever i try to download any song it keeps saying that there is a Hash error.

### ISSUE THREAD

**Issue by DavidWilliamGray** [StarGazer1258/BeatDrop#132]
![hash error](https://user-images.githubusercontent.com/59534075/71781833-6c4fde80-2fd3-11ea-8714-21886e5f8b49.PNG)

**Comment by AlanoLeider** [comment]
i got the seme error
![image](https://user-images.githubusercontent.com/30403463/71782113-58808a00-2f8b-11ea-8d7e-75c8bb56c3fe.png)

**Comment by jkreezan** [comment]
I am having the same problem

**Comment by DavidWilliamGray** [comment]
Im going to delete it and then redownload it and ill update you guys if it works

**Comment by DavidWilliamGray** [comment]
Nope it did not work :(

**Comment by Snouckeur** [comment]
Same issue on my WIN10 PC.
![image](https://user-images.githubusercontent.com/59575594/71836004-4d287e00-30b3-11ea-9a12-d41c1dad7390.png)

**Comment by hydroculator** [comment]
Same here

**Comment by aoighost** [comment]
same here

**Comment by mavericksv** [comment]
I am also having this issue

**Comment by ratcom** [comment]
same here too :(

**Comment by cherry25565** [comment]
Same problem over here

**Comment by Spici23** [comment]
I have the same problem someone have an idea how to fix

**Comment by shininghero** [comment]
It appears to be a server issue on BeatSaver's part.  Their server instance is not properly handling the www subdomain.
API requests to beatsaver.com/* work fine, but requests to www.beatsaver.com/* give the below error:

    404 Site www.beatsaver.com is not served on this interface

**Comment by Hotrodkid96** [comment]
same

**Comment by StarGazer1258** [comment]
Duplicate of #121. Further discussion will be tracked there.
