### ISSUE TITLE
BeatDrop

### ISSUE THREAD

**Issue by ZE12** [StarGazer1258/BeatDrop#136]
**Environment:**
Device - Device Manufacturer, Model Number, and Revision
OS - Operating System Type, Version, and Build Number
BeatDrop Version - BeatDrop Version including build tags
![7466d58c3b2aa988f82e8913d9442067](https://user-images.githubusercontent.com/25000594/71804128-e3ee3e00-30a5-11ea-9068-ad26f5778fae.png)

**Description of bug:**

**Steps to reproduce:**

**Expected behavior:**

**Actual Behavior**
A clear and concise description of what actually happened.

**Screenshots:**

**Comment by aoighost** [comment]
same here

**Comment by aoighost** [comment]
I forgot to set the proper install directory and that caused this for me

**Comment by StarGazer1258** [comment]
Further information is required. Please fill out all sections of the bug report template and this issue will be reopened.
