### ISSUE TITLE
Crash and Unable to downlaod songs

### ISSUE THREAD

**Issue by AbsoluteMarmalade** [StarGazer1258/BeatDrop#138]
**Environment:**
Device - Device Manufacturer, Model Number, and Revision
OS - Operating System Type, Version, and Build Number
BeatDrop Version - BeatDrop Version including build tags

**Description of bug:**

**Steps to reproduce:**

**Expected behavior:**

Changing folder causes game to crash 
downloading songs

**Actual Behavior**
A clear and concise description of what actually happened.
beatdrop crashes and provides error
hash 906160fdf808e2f34f33c2a5920118855c065d. when attempting to download songs

**Screenshots:**
![image](https://user-images.githubusercontent.com/22688858/71994897-70a41380-31ee-11ea-885c-b2e6b229e7c9.png)

**Comment by jpallent** [comment]
i cant donload or see the Mods either

**Comment by StarGazer1258** [comment]
Further information is required. Please fill out all sections of the bug report template and this issue will be reopened.
