### ISSUE TITLE
Songs not loading from internet

### ISSUE THREAD

**Issue by oookotooo** [StarGazer1258/BeatDrop#163]
Very nice application.

But it would be great if it can load songs from https://bsaber.com/
I have just installed it and it is not loading songs.

Aslo can you enable one click install in it?
![image](https://user-images.githubusercontent.com/15310858/73245962-26430080-41b6-11ea-9c5e-ab04b193e2cf.png)

**Comment by Mahekaru** [comment]
pull requests
#162  and @ #158 have solutions to fix this. They just have to go through the process

**Comment by oookotooo** [comment]
Thanks, waiting for update
