### ISSUE TITLE
Crash after loading some songs

### ISSUE THREAD

**Issue by TDroogers** [StarGazer1258/BeatDrop#169]
**Environment:**
Device - Computer
OS - Windows 10
BeatDrop Version - 2.6.2

**Description of bug:**
It crashed after loading Rasputin (Funk over...)

**Steps to reproduce:**
1. Go to 'Libary -> songs'
2. Click on 'Rasputin (Funk over...)'
4. See error in schreenshot

**Expected behavior:**
I should be able to delete this song

**Actual Behavior**
TypeError
    in t
    in Connect(t)
    in qa
    in div
    in div
    in t
    in Connect(t)
    in div
    in t
    in Connect(t)
    in t
    in t
    in t

**Screenshots:**
<img width="818" alt="2020-02-07_21h12_23" src="https://user-images.githubusercontent.com/34547552/74062537-c129af00-49ee-11ea-9a51-2aa11a6d344d.png">

**Comment by DeeJanuz** [comment]
Having the same issue. Happens on the song "Africa" by Toto as well.
