### ISSUE TITLE
Endless "Scanning for songs". BeatDrop is not working

### ISSUE THREAD

**Issue by qzmenko** [StarGazer1258/BeatDrop#17]
**Environment:**
Device - PC
OS - Windows 10 Home, Version 1809, Build 17763.437
BeatDrop Version - 2.1.8

**Description of bug:**
When I run BeatDrop, I always get a pop-up with the message "Scanning for songs" and nothing happens. I can't close it, and BeatDrop doesn't work for me. My "CustomSongs" folder only contains 1 song. I tried reinstalling Beat Drop but it didn't help.

**Steps to reproduce:**
1. I'm just trying to run BeatDrop.

**Screenshots:**
![Screenshot](https://image.prntscr.com/image/WgVMbkNzSSaAW7PJ_hmj3w.png)

**Comment by StarGazer1258** [comment]
This is a known issue with old song scanning code. I am working on rewriting this for the next release so that it will work more reliably. For now the only fix is to do a fresh install of BeatSaber and delete the ``%APPDATA%/beatdrop`` folder.

**Comment by StarGazer1258** [comment]
Should be fixed in 2.3.0-beta (d2c74349376143d2b6c8446629ec65f999c6f985). Will be released publicly soon.
