### ISSUE TITLE
Suggestion: Download all maps

### ISSUE THREAD

**Issue by ToRRent1812** [StarGazer1258/BeatDrop#18]
The only feature I used in Beatdrop 1 was download all button, where I can fill my library with all maps. It would be nice to have similar feature in BD2 with some more filters like minimum rating/difficulty to put a map inside queue.

**Comment by StarGazer1258** [comment]
Unfortunately downloading all songs in bulk would be very intensive on the BeatSaver server and is not recommended with the massive amount of songs available now. The download all button was a feature built for the relatively small amount of songs available at the time, certainly not the amount we have now, so I have no intentions of reintegrating it into BeatDrop 2, sorry.
