### ISSUE TITLE
ALWAYS CRASHES 

### ISSUE THREAD

**Issue by CallMeSkulls** [StarGazer1258/BeatDrop#204]
**Environment:**
Device - Device Manufacturer, Model Number, and Revision
OS - Operating System Type, Version, and Build Number
BeatDrop Version - BeatDrop Version including build tags

**Description of bug:**

**Steps to reproduce:**

**Expected behavior:**

**Actual Behavior**
A clear and concise description of what actually happened.

**Screenshots:**

**Comment by thomasfrobieter** [comment]
Holy crap guys. Task templates are not for ignoring them and spamming angry shit in the issue title.

@StarGazer1258 I'm so happy i never have end users in my repositories, this must be horrible to maintain.

**Comment by CallMeSkulls** [comment]
Beatdrop is TRASH. Get beatlist. Always works, servers never have issues, and you can easily download songs. No hard setup.
