### ISSUE TITLE
Does not work in Beat Saber 1.0.1

### ISSUE THREAD

**Issue by nvirth** [StarGazer1258/BeatDrop#33]
**Description of bug:**
BeatDrop does not work for me in BeatSaber 1.0.1.
I can see my playlists in the game, but selecting them does not filter the songs to the playlist.

Moreover, after installing BeatDrop, filtering provided by [SongBrowser](https://github.com/halsafar/BeatSaberSongBrowser) is broken. Click on Filters activates the filter (filter will be marked with green), but the songs won't be filtered

**Environment:**
Device - Oculus Rift S
OS - Edition: Windows 10 Education, Version: 1803, OS build: 17134.765
BeatDrop Version - 2.3.3
BeatSaber Version - 1.0.1

Installed mods:

| Mod Name | Version | Game V. | Author | Category | Upload Date |
| -------- | ------- | ------- | ------ | -------- | ----------- |
| BS Utils | 1.3.4 | 1.0.0 | Kyle 1413 | Libraries | 5/28/2019, 7:57:07 PM |
| BSIPA | 3.12.20 | 1.0.0 | DaNike | Core | 5/22/2019,10:51:09 PM |
| BeatSaverDownloader | 3.3.6 | 1.0.0 | Kyle 1413 | Core | 5/28/2019,11:35:23 PM |
| CustomUI | 1.5.8 | 1.0.0 | Kyle 1413 | Libraries | 5/21/2019,1:12:25 AM |
| DarthMaul | 0.7.2 | 1.0.0 | Kyle 1413 | Gameplay | 5/21/2019,1:21:08 AM |
| IntroSkip | 2.2.3 | 1.0.0 | Kyle 1413 | Practice/Training | 5/21/2019,1:26:13 AM |
| MappingExtensions | 1.2.2 | 1.0.0 | Kyle 1413 | Libraries | 5/21/2019,1:27:57 AM |
| NotesLeftCounter | 1.1.1 | 1.0.0 | Kyle 1413 | Ul Enhancements | 5/21/2019,1:28:31 AM |
| ScoreSaber | 2.1.7 | 1.0.0 | Umbranox | Core | 5/24/2019,10:05:08 PM |
| SongBrowser | 4.1.0 | 1.0.0 | halsafar | Ul Enhancements | 5/26/2019,8:20:55 PM |
| SongCore | 1.0.0 | 1.0.0 | Kyle 1413 | Libraries | 5/21/2019,1:17:13 AM |
| SongLoader | 7.0.0 | 1.0.0 | Kyle 1413 | Core | 5/21/2019,1:17:59 AM |

**Comment by nvirth** [comment]
Could attach screenshot or video if you thing it could be of any help

**Comment by nvirth** [comment]
I also have Mod Assistant 1.0.19 installed.
It seems after I installed Beat Drop, Mod Assistant forgot most of the mods installed.
So the list of my installed mods is now correctly displayed in Beat Drop, but not in Mod Assistant.
Don't know if there is any real connection with Beat Drop installation, because Mod Assistant has done similar things earlier - maybe also forgot the mod list when Beat Saber 1.0.1 upgrade happened...
[Mod Assistant currently shows this mod list for me](https://user-images.githubusercontent.com/11088526/59108362-fb601f80-893a-11e9-9b2b-7248cab2dc01.png)

**Comment by StarGazer1258** [comment]
1.0.0 mods will work on 1.0.1. The version of Beat Saber has nothing to do with this.

 If mods do not load properly, I would suggest a clean reinstall of Beat Saber, run the game once before attempting to install mods.

If you need more help, go to the [BSMG Discord](https://discord.gg/beatsabermods) and ask in the #support channel.
