### ISSUE TITLE
Strange behaviour for songs with non-standard directories

### ISSUE THREAD

**Issue by FolkSong** [StarGazer1258/BeatDrop#39]
I used to download songs manually and I just put them in a folder with the song name, rather than the numbers used by auto-downloaded songs. When I right click one of these songs in BeatDrop it seems to get confused and brings up multiple incorrect menus. [Screenshot](https://i.imgur.com/dNHdXPz.png).

**Comment by FolkSong** [comment]
Update, I decided to just re-download all of the affected songs. I'll leave this here as an FYI.

**Comment by StarGazer1258** [comment]
Probably related to #4.
