### ISSUE TITLE
BeatDrop not loading any songs (for download)

### ISSUE THREAD

**Issue by seyo-IV** [StarGazer1258/BeatDrop#43]
**Environment:**
Oculus Rift s
Windows 10 Build 1809
BeatDrop Version 2.3.3. Tried also latest(beta) got same issue.

**Description of bug:**
BeatDrop not loading any songs (for download)

**Steps to reproduce:**
1. Open BeatDrop
2. Click on 'new Songs'

**Expected behavior:**
Load some songs for download

**Actual Behavior**
Loading songs for iternity and nothing showing up.

**Comment by StarGazer1258** [comment]
Please include BeatDrop version

**Comment by anthonyhendrickson** [comment]
Same issue on BeatDrop v2.3.3 with Beat Saber v1.1.0

**Comment by StarGazer1258** [comment]
2.3.3 is not compatible with the current version of BeatSaver and Beat Saber. Please use 2.5.2-beta or wait for a stable update.

**Comment by DamCx** [comment]
Same issue with Beat Saber 1.1.0 and BeatDrop 2.5.8 (I reinstalled BeatDrop from scratch)
