### ISSUE TITLE
Searching just keeps loading

### ISSUE THREAD

**Issue by HexDevv** [StarGazer1258/BeatDrop#55]
**Environment:**
Device - Ryzen 5 1600X, GTX 970, 16GB RAM
OS - Windows 10 (running latest version)
BeatDrop Version - 2.5.5

**Description of bug:**
Attempting to search for songs but it keeps loading and doesn't stop.

**Steps to reproduce:**
1. Click on Search
2. Search up "Possession" or "1000 Cuts" (made by KUURO. Definitely on beatsaver)
3. Just keeps loading

**Expected behavior:**
Results from Beat Saver are meant to show up im pretty sure.

**Actual Behavior**
Just keeps loading

**Screenshots:**
https://got-your.bigno.se/5c86bab.png

**Comment by HexDevv** [comment]
Fixed it by changing my folder to somewhere random and pressing reset everything on the crash message

**Comment by StefanJanssen95** [comment]
Which folder? The game folder, the application folder, the image folder? 
I have the same issue and giving a more detailed desciption might help others as well.

**Comment by HexDevv** [comment]
I changed my game folder (in the settings) to a random location to force a crash.

**Comment by altskop** [comment]
This really isn't a fix though, just a workaround. I've faced this issue as well.
Should this be reopened to help track the bug down?

**Comment by HexDevv** [comment]
@altskop since the reset it's been completely fine and dandy so

**Comment by HexDevv** [comment]
@altskop reopen it if you wish

**Comment by StefanJanssen95** [comment]
@HexDevv For me it works for a day or three until it breaks again.
