### ISSUE TITLE
Songs in Library are not detected

### ISSUE THREAD

**Issue by JtheDroid** [StarGazer1258/BeatDrop#6]
**Environment:**
Device - PC
OS - Windows 10 Home, Version 1809, Build 17763.437
BeatDrop Version - 2.1.6

**Description of bug:**
On a fresh install or after scanning for songs, downloaded songs are not detected properly:
When selecting a song listed under 'BeatSaver' (as described below), it is not marked as 'In Library' and the Download button appears.
When clicking 'Download Missing Songs' for a playlist, all songs are downloaded.
After a song has been downloaded again through BeatDrop, it is marked correctly until scanning for songs again.
The songs still do show up under Library -> Songs

**Steps to reproduce:**
1. Go to settings, Click on 'Scan for Songs'
2. Open a song listed under 'BeatSaver' (not 'Library')
a.1 Go to one of the 'BEATSAVER' categories (e.g. 'Top Downloaded')
a.2 Select a song
or
a.1 Search for a song
b.2 Click the result under 'BeatSaver'
3. Song is not detected as 'In Library'

**Expected behavior:**
Downloaded songs are detected (marked as 'In Library') and not downloaded unnecessarily

**Actual Behavior**
When selected via BeatSaver, songs are not detected as downloaded and will be downloaded again.
Once downloaded through BeatDrop, songs are marked as 'In Library' until restarting BeatDrop or scanning songs
When selected via Library, songs are correctly detected

**Screenshots:**
*Example: Believer (31-11)*
Song folder:
![image](https://user-images.githubusercontent.com/25618585/56021541-05ceb600-5d0a-11e9-8a09-4745ababa585.png)
Search results: (still appears in library)
![image](https://user-images.githubusercontent.com/25618585/56021875-ce143e00-5d0a-11e9-8ce9-702ed13e7a77.png)

'Library' search result:
![image](https://user-images.githubusercontent.com/25618585/56029031-cd36d880-5d19-11e9-8989-14237cdd9d33.png)
'BeatSaver' search result:
![image](https://user-images.githubusercontent.com/25618585/56028349-34538d80-5d18-11e9-8c23-e1f3f1640d30.png)
After re-downloading:
![image](https://user-images.githubusercontent.com/25618585/56028289-1c7c0980-5d18-11e9-80e5-45729e89a54d.png)

In 'Top Downloaded' list:
Initially/After scanning for songs:
![image](https://user-images.githubusercontent.com/25618585/56023095-73301600-5d0d-11e9-81a6-31f4bbc2f6a4.png)
After downloading it again:
![image](https://user-images.githubusercontent.com/25618585/56023719-ceaed380-5d0e-11e9-900e-ef62dba0a1b2.png)

**Comment by brandonhenry** [comment]
Observations: 

- The comparison for "In Library" indicators is not efficient
- Hashes for downloaded songs are all the same

Solution:

There are many, but I think I'm going to go with adding an equals method to compare songs via name, subname, authorname, and BPM

**Comment by brandonhenry** [comment]
Hashes weren't actually being generated. updated!

**Comment by StarGazer1258** [comment]
Seems as this has been fixed by #36.
