### ISSUE TITLE
"Oops" screen when clicking "songs"; reset doesn't help

### ISSUE THREAD

**Issue by omgitsraven** [StarGazer1258/BeatDrop#62]
**Environment:**
Device - Oculus Rift CV1
OS - Windows 10 Home 1809
BeatDrop Version - v2.5.6 and v2.5.7-beta

**Description of bug:**
Clicking `SONGS > LIBRARY > Songs` always shows the "Oops! BeatDrop has crashed!" screen, even after clicking "reset everything", even after uninstalling BeatDrop, even when running as administrator.

Viewing mods works. Viewing playlists works, even.

In 2.5.5, trying to view Songs would give me a bunch of red errors about not being able to find songs that I've already deleted (in Beat Saber) and then give me an empty list (even though I had other songs still installed).

Doing "scan for songs" correctly sees the 28 songs that I have installed.

**Steps to reproduce:**
1. Launch BeatDrop
2. Click 'Remind me Later'
3. Click `SONGS` if it isn't already expanded
4. Click `SONGS > LIBRARY > Songs`
5. The error appears (for me)

**Expected behavior:**
The list of installed songs would appear.

**Actual Behavior**
The error screen appears, suggesting a reset, which doesn't fix it.

I'm going to try a full un/reinstall at some point, but I thought I'd mention it first, in case you wanted me to check some config files to identify why it might be happening.

**Comment by StarGazer1258** [comment]
If it’s not too large, could you upload a zip of you CustomLevels folder?

**Comment by omgitsraven** [comment]
It's fairly large, but here: http://ravenworks.ca/temp/CustomLevels_bugreport.rar

**Comment by finalexit** [comment]
Same problem here, out of 255 songs over half of them caused this error if they were in my library.  I even tried deleting the songs and redownloading through beatdrop but it didn't help.

**Comment by powerufljl** [comment]
Same issue for me, but I can't even open my song library without the instant crashing of beatdrop

**Comment by finalexit** [comment]
> 
> 
> Same issue for me, but I can't even open my song library without the instant crashing of beatdrop

The latest beta fixed it for me https://github.com/StarGazer1258/BeatDrop/releases/tag/v2.5.8-beta

**Comment by StarGazer1258** [comment]
Yes, this issue should be fixed in 2.5.8-beta

**Comment by omgitsraven** [comment]
Yep, all better, thanks!! (2.5.8-beta actually gave me the "oops" screen on launch exactly once, but after clicking "reset everything" on that, it's been fine since.)
