### ISSUE TITLE
App can't load songs with non-standard folder names

### ISSUE THREAD

**Issue by zxsdklfhskyrvk** [StarGazer1258/BeatDrop#64]
**Environment:**
Device - n/a
OS - Windows 10
BeatDrop Version - Latest

**Description of bug:**
BeatDrop will not load my library, possibly because I've altered the folder names to be non-standard. This is NOT about special characters.  All characters are standard ascii.

**Steps to reproduce:**
1. Rename all song folders to non-standard syntax.  
2. Load app
3. Try to access library
4.  Nothing loads

**Expected behavior:**
All songs should load regardless of the folder names.  Folder names are not the way to identify the songs.  That is the point of the json/dat files.

**Actual Behavior**
N0 songs load in the library

**Comment by StarGazer1258** [comment]
Songs are identified by dat files, not folder names. However, BeatDrop cannot locate these files if you have moved/renamed them externally. If you have done so, please use the “Scan for Songs” button located in settings to relocate these songs.
