### ISSUE TITLE
"Oops" screen when click on song in local library

### ISSUE THREAD

**Issue by zizip0p** [StarGazer1258/BeatDrop#66]
**Environment:**
OS - Windows 10 x64
BeatDrop Version - 2.5.8

**Description of bug:**
"Oops" screen when click on song in local library

**Steps to reproduce:**
1. Run BeatDrop
2. Search "angelic" for example
3. Select "Xi - Angelic Party" and download it
4. Choose Songs and click on "Xi - Angelic Party"

**Сause of error**
The error occurs because _songAuthorName in info.dat is empty:
"_songAuthorName": "",

I gave a "Xi - Angelic Party" for example, there are a lot of such tracks

**Comment by StarGazer1258** [comment]
See #87.
