### ISSUE TITLE
Crashes immediately after changing file directory

### ISSUE THREAD

**Issue by Mulyac45** [StarGazer1258/BeatDrop#69]

**Comment by StarGazer1258** [comment]
Need more info than this. Please follow the bug report template.

**Comment by RabidGlitter** [comment]
Same here, Mulyac. 
StarGazer, I've never filed a bug report before but hopefully I'll get you the info you need.

**Comment by wesaraw** [comment]
I have also had this issue and many other people have. I've collected all of the issue submissions that are the same as this. They are: #77 #73 #72 #69

**Comment by StarGazer1258** [comment]
Further information is required. Please fill out all sections of the bug report template and this issue will be reopened.
