### ISSUE TITLE
beatdrop crashes

### ISSUE THREAD

**Issue by jack652** [StarGazer1258/BeatDrop#72]
**Environment:**
Device - desktop pc
OS - windows 10
BeatDrop Version - 2.5.9

**Description of bug:**
i crashed when clicking on "waiting for love" song in my library
(TypeError
    in t
    in Connect(t)
    in Ga
    in div
    in div
    in t
    in Connect(t)
    in div
    in t
    in Connect(t)
    in t
    in t
    in t)

**Expected behavior:**
it shouldn't crash

**Actual Behavior**
ita crashes

**Comment by wesaraw** [comment]
I have also had this issue and many other people have. I've collected all of the issue submissions that are the same as this. They are: #77 #73 #72 #69

**Comment by TNTgamer71** [comment]
Yep, having the same problem

**Comment by StarGazer1258** [comment]
Possibly related to #87.
