### ISSUE TITLE
Beat hub just doesn't work it says 'TypeError     in t     in Connect(t)     in div     in t     in Connect(t)     in t     in t     in t'

### ISSUE THREAD

**Issue by Roseskul** [StarGazer1258/BeatDrop#73]
**Environment:**
Device - Device Manufacturer, Model Number, and Revision
OS - Operating System Type, Version, and Build Number
BeatDrop Version - BeatDrop Version including build tags

**Description of bug:**

**Steps to reproduce:**

**Expected behavior:**

**Actual Behavior**
A clear and concise description of what actually happened.

**Screenshots:**

**Comment by wesaraw** [comment]
I have this same problem but I filled out the error log a bit more than this. Its error #77 if it helps. At this moment tho it has no answers

**Comment by wesaraw** [comment]
I have also had this issue and many other people have. I've collected all of the issue submissions that are the same as this. They are: #77 #73 #72 #69

**Comment by valleydev** [comment]
Same here. Occurs only when viewing details of Song named "Enter Enter Mission" by Ankou Team

**Comment by StarGazer1258** [comment]
Further information is required. Please fill out all sections of the bug report template and this issue will be reopened.
