### ISSUE TITLE
Crashed Beat Drop 

### ISSUE THREAD

**Issue by wesaraw** [StarGazer1258/BeatDrop#77]
**Environment:**
Device - What device?
OS - Windows 10 Home, v1903, and 18362.239
BeatDrop Version - v2.6.0 (not sure what the tags are)

**Description of bug:**
fresh install>just got to the menu to select customer song dir>just after I select the dir @ 'E:\Sorting Project\Steam\steamapps\common\Beat Saber\Custom Songs' I get the crash>crash says the following;

"TypeError
    in t
    in Connect(t)
    in div
    in t
    in Connect(t)
    in t
    in t
    in t
"

**Steps to reproduce:**
1. Go to 'Install beat drop and upon dir selection'
2. Click on 'Choose Folder>[inset dir]>select folder'
3. Scroll down to ''

**Expected behavior:**
I just downloaded this program so I'm not exactly sure what I should expect? Hopefully something good.

**Actual Behavior**
Crash Menu

**Screenshots:**
If needed Ill provide but I don't think this is important atm

**Comment by wesaraw** [comment]
I have also had this issue and many other people have. I've collected all of the issue submissions that are the same as this. They are: #77 #73 #72 #69

**Comment by Temmie-Nexus** [comment]
I had the same problem while the first config after installation.

It had two causes:
1.) Missing rights -> Start program as admin
2.) The path was wrong -> the direct installation directory, i.e. the folder "Beat Saber" must be specified

But now comes the next problem:

#90

**Comment by StarGazer1258** [comment]
Make sure that you set the directory to the Base Game directory, not CustomSongs.
