### ISSUE TITLE
Keeps Crashing After initial Set up

### ISSUE THREAD

**Issue by irenemarquez82** [StarGazer1258/BeatDrop#80]
**Environment:**
Device - Device Manufacturer, Model Number, and Revision
OS - Operating System Type, Version, and Build Number
BeatDrop Version - BeatDrop Version including build tags

**Description of bug:**
I just installed it. Cant choose Oculus folder and when I choose the Steam folder and 13.0 or any of the next settings it crashes.

**Comment by StarGazer1258** [comment]
Further information is required. Please fill out all sections of the bug report template and this issue will be reopened.
