### ISSUE TITLE
it cant download on my pc

### ISSUE THREAD

**Issue by unicourt99** [StarGazer1258/BeatDrop#82]
**Environment:**
Device - Device Manufacturer, Model Number, and Revision
OS - Operating System Type, Version, and Build Number
BeatDrop Version - BeatDrop Version including build tags

**Description of bug:**

**Steps to reproduce:**

**Expected behavior:**

**Actual Behavior**
A clear and concise description of what actually happened.

**Screenshots:**

**Comment by b-rad15** [comment]
You gave zero details about the problem at the very least mention what system you are using or even what you did to download it. Something not downloading sounds like a browser issue if it downloaded but didnt install that might be an installer issue. 

Make sure you are using this link https://github.com/StarGazer1258/BeatDrop/releases/tag/v2.5.9 and downloading the setup executable.

**Comment by StarGazer1258** [comment]
Further information is required. Please fill out all sections of the bug report template and this issue will be reopened.
