### ISSUE TITLE
4.5.9 & 4.6.0 Search function not working

### ISSUE THREAD

**Issue by SonicRising** [StarGazer1258/BeatDrop#85]
PC
Win 10 
V 4.5.9/4.6.0

Click on Search, type song to search, then the blue search icon just sits there spinning forever.  
 Internet connection is perfect.  Was able to search one song before it started doing this.  Have uninstalled and reinstalled both versions more than once, still no change.

**Comment by StarGazer1258** [comment]
How did you go about uninstalling/reinstalling the application? If you did not delete ``%APPDATA%\beatdrop`` the bug may persist. You may also try using the "Reset Everything" button in settings, which should have the same effect.

**Comment by SonicRising** [comment]
There is no Reset Everything button in settings. What am I missing here.
Here is a pic. The only thing below what you see are the credits.

**Comment by SonicRising** [comment]
Tried to send the pic but I won't go.

**Comment by SonicRising** [comment]
Nvm. I deleted the file and it works now. Thanks for your help.

**Comment by StarGazer1258** [comment]
Closing as issue appears to be resolved.
