### ISSUE TITLE
Freeze when pressing "Install" on mods

### ISSUE THREAD

**Issue by MatrikMoon** [StarGazer1258/BeatDrop#9]
**Environment:**
Device - CyperpowerPC Tracer
OS - Windows 10, 10.0.17134 Build 17134
BeatDrop Version - 2.1.6

**Description of bug:**
When pressing "Install" on any mod, the program freezes. In the log, it appears to be attempting to install repetitively, infinitely

**Steps to reproduce:**
1. Install beat saber (I didn't open it before step 2)
2. Install beatdrop
3. Press "install" on any mod
4. Be frozen

Fix:
1. Install bsipa through the other mod manager

**Expected behavior:**
Mod is installed

**Actual Behavior**
Program freezes

**Comment by TuTAH1** [comment]
Have this bug on 2.5.5 vesion – tried uninstall including beatdrop folder in AppData and install again – isn't fix
