### ISSUE TITLE
Unable to finish initial setup

### ISSUE THREAD

**Issue by LAGIdiot** [StarGazer1258/BeatDrop#90]
**Environment:**
Device - Custom build PC
OS - Windows 10 Pro, 1903, 18362.388
BeatDrop Version - 2.5.9, 2.6.1-beta
Beat Saber - 1.4.0

**Description of bug:**
Unable to finish initial setup due to game version selector not showing any applicable game versions. Which in end means deactivated continue button.

**Steps to reproduce:**
1. Clean installation of Beat Saber from Steam (current version 1.4.0)
2. Clean installation of BeatDrop.
3. Opening BeatDrop
4. Getting stuck in Initial Setup

**Expected behavior:**
In drop box under Game Version I would expect some versions of game to select from including mine version (1.4.0) of game. Which after selection would activate continue button.

**Actual Behavior**
Drop box under Game Version contains only Choose One option. Which selection does not activate continue button.

**Screenshots:**
![BeatDrop_Bug_InitialSetup_GameVersionSelector](https://user-images.githubusercontent.com/3093101/66567001-932e7e00-eb66-11e9-8507-09121e6a4556.png)

**Comment by Temmie-Nexus** [comment]
Same Problem here. :/

**Comment by brolyls** [comment]
same problem here, worked fine a few days ago all of the sudden i get this problem

**Comment by Ruben-E** [comment]
Same here

**Comment by efrenmanuel** [comment]
Same here, it seems to be due to it being unable to fetch the version list from BeatMods.com as it's down right now.

**Comment by VivaLaPanda** [comment]
Could also just be that the new Beat Saber versions aren't in the listing.

**Comment by LAGIdiot** [comment]
> Could also just be that the new Beat Saber versions aren't in the listing.

There is nothing expect "Choose One" in listing of versions. I would understand if only newest version was missing but that is not the case.

**Comment by Ruben-E** [comment]
Still no version? For me it is fixed since beatmods.com is back online.

**Comment by LAGIdiot** [comment]
Yeah it seems that problem for which was this issue created is fixed. And as @Ruben-E pointed out it is probably because site beatmods.com is back online.

**Comment by Setarii** [comment]
Is this issue going to be fixed? It's back again as of 4:14 AM MST 12/5/2019 (5/12/2019 for EU).
