### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by IAmCorbin** [StarGazer1258/BeatDrop#93]
**Environment:**
OS - Windows 10
BeatDrop Version - 2.5.9

**Description of bug:**
Installed, set game directory, song scanner finished, clicked on Songs. Error report view shows.

TypeError
    in Le
    in div
    in li
    in t
    in Connect(t)
    in div
    in t
    in ul
    in t
    in Connect(t)
    in Qa
    in Ga
    in div
    in div
    in t
    in Connect(t)
    in div
    in t
    in Connect(t)
    in t
    in t
    in t

**Comment by StarGazer1258** [comment]
Further information is required. Please fill out all sections of the bug report template and this issue will be reopened.
