### ISSUE TITLE
Crashed by the beginning

### ISSUE THREAD

**Issue by ImsoGoat** [StarGazer1258/BeatDrop#95]
![screenError](https://user-images.githubusercontent.com/57302367/68077167-4b92bf00-fdbf-11e9-84d3-51e8c301e54e.PNG)

**Comment by ImsoGoat** [comment]
can't use the application :(

**Comment by StarGazer1258** [comment]
Further information is required. Please fill out all sections of the bug report template and this issue will be reopened.
